language: node_js

node_js:
  - node
  - 9

env:
  ARK_CI_TEST: true

before_install:
  - npm install yarn lerna
  - yarn config set cache-folder $HOME/.yarn-cache

install:
  - yarn bootstrap

stages:
  - lint
  - depcheck
  - test
  # TODO
  # - browser_test

scripts:
  - yarn test:coverage

jobs:
  include:
    - stage: lint
      script: yarn lint
    # To lint the version 9 too
    - stage: lint
      node_js: 9
      script: yarn lint

    - stage: depcheck
      script: yarn depcheck
    # To lint the version 9 too
    - stage: depcheck
      node_js: 9
      script: yarn depcheck

    # TODO
    # - stage: browser_test
    #   script: yarn test:coverage
    # - stage: browser_test
    #   node_js: 9
    #   script: yarn test:coverage

cache:
  yarn: true # This wouldn't do anything because it needs a yarn.lock
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    # - node_modules
    # - packages/**/node_modules
